### DISCUSSION TITLE
[Question] Extension support: json1, fts5

### DISCUSSION THREAD

**Discussion by rodydavis** [powersync-ja/sqlite_async.dart#29] [Q&A] [answered]
How can I install extensions for SQLite?

In drift for example I declare a build.yaml:

```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          mutable_classes: true
          sql:
            dialect: sqlite
            options:
              version: "3.35"
              modules:
                - json1
                - fts5
                - math
```
